### ISSUE TITLE
`addChild` should optionally not inherit id from parent

### ISSUE THREAD

**Issue by mosharky** [westernat/AdvancementJS#10]
Currently, the `addChild` advancement id is just the parent id with the given child id appended. It would be nice to be able to give a custom id. This would be useful for modifying advancements from mods that don't adhere to the `namespace:parent/child` format that this mod assumes.

**Comment by westernat** [comment]
Actually, in event.create("advjs:test") method, the created root advancement's id is "advjs:test/root". And its children's id would be "advjs:test/child_id".
In event.get("minecraft:story/parent_id") method, its children's is would be "minecraft:story/parent_id/child_id".

So, do you mean you want the child's ID in the second example to be "minecraft:story/child_id" ?
If not, I'll give a convention: if you pass in the addChild method the full location like "advjs:custom_path", then the child's id would be the location you passed in.

**Comment by mosharky** [comment]
> So, do you mean you want the child's ID in the second example to be "minecraft:story/child_id"?

Yeah, sorry I dd mean it with `event.get()`

>  if you pass in the addChild method the full location like "advjs:custom_path", then the child's id would be the location you passed in

I tried that, and it doesn't allow it: `Non [a-z0-9/._-] character in path of location: beautify:progression/root/beautify:progression/candelabra`. Here's the code:
```js
ServerEvents.advancement(event => {
    const { PREDICATE, PROVIDER, TRIGGER } = event

    event.get('beautify:progression/root')
        .addChild('beautify:progression/candelabra', advBuilder => {
            advBuilder
                .display(displayBuilder => {
                    displayBuilder.setIcon('beautify:lamp_candelabra')
                    displayBuilder.setTitle('Wicked!')
                    displayBuilder.setDescription('Craft a candelabra')
                    displayBuilder.setFrameType(FrameType.TASK)
                    displayBuilder.setShowToast(true)
                    displayBuilder.setAnnounceToChat(true)
                })
                .criteria(criteriaBuilder => {
                    criteriaBuilder.add('obtain', TRIGGER.hasItems('beautify:lamp_candelabra'))
                })
        })
})
```

and here is the full error:
```
[11:59:51] [ERROR] ! Error in 'ServerEvents.advancement': Non [a-z0-9/._-] character in path of location: beautify:progression/root/beautify:progression/candelabra
[11:59:51] [ERROR] ! net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: beautify:progression/root/beautify:progression/candelabra
[11:59:51] [ERROR] !   at net.minecraft.resources.ResourceLocation.m_245185_(ResourceLocation.java:236)
[11:59:51] [ERROR] !   at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:38)
[11:59:51] [ERROR] !   at org.mesdag.advjs.configure.AdvBuilder.getSavePath(AdvBuilder.java:102)
[11:59:51] [ERROR] !   at org.mesdag.advjs.configure.AdvBuilder.update(AdvBuilder.java:92)
[11:59:51] [ERROR] !   at org.mesdag.advjs.configure.AdvBuilder.display(AdvBuilder.java:60)
[11:59:51] [ERROR] !   at java.lang.reflect.Method.invoke(Method.java:568)
[11:59:51] [ERROR] !   at …rhino.MemberBox.invoke(MemberBox.java:160)
[11:59:51] [ERROR] !   at …rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[11:59:51] [ERROR] !   at …rhino.Interpreter.interpretLoop(Interpreter.java:986)
[11:59:51] [ERROR] !   at …rhino.Interpreter.interpret(Interpreter.java:370)
[11:59:51] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.ArrowFunction.call(ArrowFunction.java:42)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[11:59:51] [ERROR] !   at …rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[11:59:51] [ERROR] !   at jdk.proxy1/jdk.proxy1.$Proxy146.accept(Unknown Source)
[11:59:51] [ERROR] !   at org.mesdag.advjs.configure.AdvGetter.addChild(AdvGetter.java:61)
[11:59:51] [ERROR] !   at java.lang.reflect.Method.invoke(Method.java:568)
[11:59:51] [ERROR] !   at …rhino.MemberBox.invoke(MemberBox.java:160)
[11:59:51] [ERROR] !   at …rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[11:59:51] [ERROR] !   at …rhino.Interpreter.interpretLoop(Interpreter.java:986)
[11:59:51] [ERROR] !   at …rhino.Interpreter.interpret(Interpreter.java:370)
[11:59:51] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.Context.doTopCall(Context.java:1307)
[11:59:51] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.ArrowFunction.call(ArrowFunction.java:42)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[11:59:51] [ERROR] !   at …rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[11:59:51] [ERROR] !   at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy117.onEvent(Unknown Source)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.postToHandlers(EventHandler.java:304)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:272)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:226)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:179)
[11:59:51] [ERROR] !   at net.minecraft.server.ServerAdvancementManager.handler$dei000$advjs$advJS$remove(ServerAdvancementManager.java:543)
[11:59:51] [ERROR] !   at net.minecraft.server.ServerAdvancementManager.m_5787_(ServerAdvancementManager.java)
[11:59:51] [ERROR] !   at net.minecraft.server.ServerAdvancementManager.m_5787_(ServerAdvancementManager.java:24)
[11:59:51] [ERROR] !   at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13)
[11:59:51] [ERROR] !   at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[11:59:51] [ERROR] !   at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[11:59:51] [ERROR] !   at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69)
[11:59:51] [ERROR] !   at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:59:51] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[11:59:51] [ERROR] !   at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[11:59:51] [ERROR] !   at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
[11:59:51] [ERROR] !   at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
[11:59:51] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[11:59:51] [ERROR] !   at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
[11:59:51] [ERROR] !   at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
[11:59:51] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
[11:59:51] [ERROR] !   at net.minecraft.server.MinecraftServer.m_129861_(MinecraftServer.java:1345)
[11:59:51] [ERROR] !   at net.minecraft.server.commands.ReloadCommand.m_138235_(ReloadCommand.java:22)
[11:59:51] [ERROR] !   at net.minecraft.server.commands.ReloadCommand.m_287964_(ReloadCommand.java:53)
[11:59:51] [ERROR] !   at MC-BOOTSTRAP/brigadier@1.1.8/com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[11:59:51] [ERROR] !   at net.minecraft.commands.Commands.m_242674_(Commands.java:257)
[11:59:51] [ERROR] !   at net.minecraft.commands.Commands.m_230957_(Commands.java:237)
[11:59:51] [ERROR] !   at …kubejs.core.MinecraftServerKJS.kjs$runCommandSilent(MinecraftServerKJS.java:60)
[11:59:51] [ERROR] !   at java.lang.reflect.Method.invoke(Method.java:568)
[11:59:51] [ERROR] !   at …rhino.MemberBox.invoke(MemberBox.java:160)
[11:59:51] [ERROR] !   at …rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[11:59:51] [ERROR] !   at …rhino.Interpreter.interpretLoop(Interpreter.java:986)
[11:59:51] [ERROR] !   at …rhino.Interpreter.interpret(Interpreter.java:370)
[11:59:51] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.Context.doTopCall(Context.java:1307)
[11:59:51] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.ArrowFunction.call(ArrowFunction.java:42)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[11:59:51] [ERROR] !   at …rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[11:59:51] [ERROR] !   at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy117.onEvent(Unknown Source)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.postToHandlers(EventHandler.java:304)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:272)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:226)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:189)
[11:59:51] [ERROR] !   at …kubejs.server.KubeJSServerEventHandler.serverStarting(KubeJSServerEventHandler.java:70)
[11:59:51] [ERROR] !   at dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:90)
[11:59:51] [ERROR] !   at dev.architectury.event.forge.__EventHandlerImplCommon_event_ServerStartingEvent.invoke(.dynamic)
[11:59:51] [ERROR] !   at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
[11:59:51] [ERROR] !   at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
[11:59:51] [ERROR] !   at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
[11:59:51] [ERROR] !   at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:111)
[11:59:51] [ERROR] !   at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:67)
[11:59:51] [ERROR] !   at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634)
[11:59:51] [ERROR] !   at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
[11:59:51] [ERROR] !   at java.lang.Thread.run(Thread.java:833)
```

**Comment by westernat** [comment]
That is what I will implement in next version. So the error throws here.



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/17/2024 01:04 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [westernat/AdvancementJS] `addChild` should optionally not inherit id from parent (Issue #10) |

So, do you mean you want the child's ID in the second example to be "minecraft:story/child_id"?

Yeah, sorry I dd mean it with event.get()

if you pass in the addChild method the full location like "advjs:custom_path", then the child's id would be the location you passed in

I tried that, and it doesn't allow it: Non [a-z0-9/._-] character in path of location: beautify:progression/root/beautify:progression/candelabra. Here's the code:

ServerEvents.advancement(event=>{const{PREDICATE,PROVIDER,TRIGGER}=eventevent.get('beautify:progression/root').addChild('beautify:progression/candelabra',advBuilder=>{advBuilder.display(displayBuilder=>{displayBuilder.setIcon('beautify:lamp_candelabra')displayBuilder.setTitle('Wicked!')displayBuilder.setDescription('Craft a candelabra')displayBuilder.setFrameType(FrameType.TASK)displayBuilder.setShowToast(true)displayBuilder.setAnnounceToChat(true)}).criteria(criteriaBuilder=>{criteriaBuilder.add('obtain',TRIGGER.hasItems('beautify:lamp_candelabra'))})})})

and here is the full error:

[11:59:51] [ERROR] ! Error in 'ServerEvents.advancement': Non [a-z0-9/._-] character in path of location: beautify:progression/root/beautify:progression/candelabra
[11:59:51] [ERROR] ! net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: beautify:progression/root/beautify:progression/candelabra
[11:59:51] [ERROR] !   at net.minecraft.resources.ResourceLocation.m_245185_(ResourceLocation.java:236)
[11:59:51] [ERROR] !   at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:38)
[11:59:51] [ERROR] !   at org.mesdag.advjs.configure.AdvBuilder.getSavePath(AdvBuilder.java:102)
[11:59:51] [ERROR] !   at org.mesdag.advjs.configure.AdvBuilder.update(AdvBuilder.java:92)
[11:59:51] [ERROR] !   at org.mesdag.advjs.configure.AdvBuilder.display(AdvBuilder.java:60)
[11:59:51] [ERROR] !   at java.lang.reflect.Method.invoke(Method.java:568)
[11:59:51] [ERROR] !   at …rhino.MemberBox.invoke(MemberBox.java:160)
[11:59:51] [ERROR] !   at …rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[11:59:51] [ERROR] !   at …rhino.Interpreter.interpretLoop(Interpreter.java:986)
[11:59:51] [ERROR] !   at …rhino.Interpreter.interpret(Interpreter.java:370)
[11:59:51] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.ArrowFunction.call(ArrowFunction.java:42)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[11:59:51] [ERROR] !   at …rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[11:59:51] [ERROR] !   at jdk.proxy1/jdk.proxy1.$Proxy146.accept(Unknown Source)
[11:59:51] [ERROR] !   at org.mesdag.advjs.configure.AdvGetter.addChild(AdvGetter.java:61)
[11:59:51] [ERROR] !   at java.lang.reflect.Method.invoke(Method.java:568)
[11:59:51] [ERROR] !   at …rhino.MemberBox.invoke(MemberBox.java:160)
[11:59:51] [ERROR] !   at …rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[11:59:51] [ERROR] !   at …rhino.Interpreter.interpretLoop(Interpreter.java:986)
[11:59:51] [ERROR] !   at …rhino.Interpreter.interpret(Interpreter.java:370)
[11:59:51] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.Context.doTopCall(Context.java:1307)
[11:59:51] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.ArrowFunction.call(ArrowFunction.java:42)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[11:59:51] [ERROR] !   at …rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[11:59:51] [ERROR] !   at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy117.onEvent(Unknown Source)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.postToHandlers(EventHandler.java:304)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:272)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:226)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:179)
[11:59:51] [ERROR] !   at net.minecraft.server.ServerAdvancementManager.handler$dei000$advjs$advJS$remove(ServerAdvancementManager.java:543)
[11:59:51] [ERROR] !   at net.minecraft.server.ServerAdvancementManager.m_5787_(ServerAdvancementManager.java)
[11:59:51] [ERROR] !   at net.minecraft.server.ServerAdvancementManager.m_5787_(ServerAdvancementManager.java:24)
[11:59:51] [ERROR] !   at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13)
[11:59:51] [ERROR] !   at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[11:59:51] [ERROR] !   at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[11:59:51] [ERROR] !   at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69)
[11:59:51] [ERROR] !   at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:59:51] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[11:59:51] [ERROR] !   at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[11:59:51] [ERROR] !   at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
[11:59:51] [ERROR] !   at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
[11:59:51] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[11:59:51] [ERROR] !   at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
[11:59:51] [ERROR] !   at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
[11:59:51] [ERROR] !   at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
[11:59:51] [ERROR] !   at net.minecraft.server.MinecraftServer.m_129861_(MinecraftServer.java:1345)
[11:59:51] [ERROR] !   at net.minecraft.server.commands.ReloadCommand.m_138235_(ReloadCommand.java:22)
[11:59:51] [ERROR] !   at net.minecraft.server.commands.ReloadCommand.m_287964_(ReloadCommand.java:53)
[11:59:51] [ERROR] !   at ***@***.***/com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[11:59:51] [ERROR] !   at net.minecraft.commands.Commands.m_242674_(Commands.java:257)
[11:59:51] [ERROR] !   at net.minecraft.commands.Commands.m_230957_(Commands.java:237)
[11:59:51] [ERROR] !   at …kubejs.core.MinecraftServerKJS.kjs$runCommandSilent(MinecraftServerKJS.java:60)
[11:59:51] [ERROR] !   at java.lang.reflect.Method.invoke(Method.java:568)
[11:59:51] [ERROR] !   at …rhino.MemberBox.invoke(MemberBox.java:160)
[11:59:51] [ERROR] !   at …rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[11:59:51] [ERROR] !   at …rhino.Interpreter.interpretLoop(Interpreter.java:986)
[11:59:51] [ERROR] !   at …rhino.Interpreter.interpret(Interpreter.java:370)
[11:59:51] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.Context.doTopCall(Context.java:1307)
[11:59:51] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.ArrowFunction.call(ArrowFunction.java:42)
[11:59:51] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[11:59:51] [ERROR] !   at …rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[11:59:51] [ERROR] !   at …rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[11:59:51] [ERROR] !   at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy117.onEvent(Unknown Source)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.postToHandlers(EventHandler.java:304)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:272)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:226)
[11:59:51] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:189)
[11:59:51] [ERROR] !   at …kubejs.server.KubeJSServerEventHandler.serverStarting(KubeJSServerEventHandler.java:70)
[11:59:51] [ERROR] !   at dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:90)
[11:59:51] [ERROR] !   at dev.architectury.event.forge.__EventHandlerImplCommon_event_ServerStartingEvent.invoke(.dynamic)
[11:59:51] [ERROR] !   at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
[11:59:51] [ERROR] !   at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
[11:59:51] [ERROR] !   at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
[11:59:51] [ERROR] !   at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:111)
[11:59:51] [ERROR] !   at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:67)
[11:59:51] [ERROR] !   at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634)
[11:59:51] [ERROR] !   at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
[11:59:51] [ERROR] !   at java.lang.Thread.run(Thread.java:833)

**Comment by westernat** [comment]
one more thing, in next version
you can easily pass in ```candelabra``` to ```addChild```, then the child's id will automatically wrap to 
```beautify:progression/candelabra```

**Comment by mosharky** [comment]
ah okay, thanks
